# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoviesPerformances',
        ),
        migrations.AddField(
            model_name='movies',
            name='booking_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movies',
            name='perform_date',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movies',
            name='start_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
