# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0002_auto_20170823_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesPerformances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_code', models.CharField(default='', max_length=500)),
                ('start_time', models.CharField(default='', max_length=200)),
                ('perform_date', models.CharField(default='', max_length=500)),
                ('booking_url', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'All Perfomances',
            },
        ),
        migrations.RemoveField(
            model_name='movies',
            name='booking_url',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='perform_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='start_time',
        ),
    ]
