# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0004_moviesfulldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesfulldetails',
            name='movie_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='moviesfulldetails',
            name='movie_title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
