# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0005_auto_20170825_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersphone',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
