# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0008_movies_movie_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
