# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0009_movies_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='location',
            new_name='movie_location',
        ),
    ]
