# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0010_auto_20171106_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesperformances',
            name='booking_url',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
