# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0011_auto_20171107_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_synopsis',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
