# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0012_auto_20171107_0620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movies',
            unique_together=set([('movie_code', 'movie_location')]),
        ),
    ]
