# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0013_auto_20171107_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_featured',
            field=models.BooleanField(default=False),
        ),
    ]
