# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0014_movies_movie_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/banners'),
        ),
    ]
