# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0016_movies_movie_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_pop_thumbnail',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/popular_thumbnails'),
        ),
    ]
