# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersphones', '0018_moviesperformances_movie_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesperformances',
            name='booking_url',
            field=models.CharField(default='', max_length=20),
        ),
    ]
